[build]
outdir = "./dist"
minify = true
splitting = false
root = "."

[build.loaders]
".tsx" = "jsx"
".ts" = "js"
".jsx" = "jsx"
".js" = "js"

[build.entrypoints]
# Frontend entry point
"/src/main.tsx" = "dist/app.js"

# Backend/Functions entry point
"/functions/_middleware.ts" = "dist/middleware.js"

[jsx]
import = "react/jsx-runtime"
